name: umdois
description: umdois app
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  # webview
  flutter_webview_plugin: ^0.3.10+2

  # url_launcher
  url_launcher: ^5.4.0    # Good, any 5.4.x version where x >= 0 works.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/cannabis.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/
